language: node_js
sudo: true
dist: trusty
node_js:
  - 6
  - 8
  - 10
install:
  - yarn
script:
  - npm run lint
  - npm test
notifications:
  email:
    on_failure: change
after_success:
  - npm run coveralls
